### ISSUE TITLE
Delete logs files if size is greater than a defined value

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_CORE#111]
Delete logs files if the size is greater than a defined value to prevent increasing indefinitely

**Comment by 3alpha** [comment]
That is a bad idea. Much better would be using: https://linux.die.net/man/8/logrotate

**Comment by pablomendezroyo** [comment]
This is great! thx for the suggestion

Closed by https://github.com/dappnode/DAppNode/issues/510 and https://github.com/dappnode/DNP_CORE/issues/113

**Comment by pablomendezroyo** [comment]
Closed by https://github.com/dappnode/DAppNode/issues/510 and https://github.com/dappnode/DNP_CORE/issues/113
