### ISSUE TITLE
Docker version conflict

### ISSUE THREAD

**Issue by fritzschoff** [dappnode/DNP_CORE#174]
Hey,
I was installing dappnode via the bash script. It downloaded it fine with the bash script sudo wget -O - https://installer.dappnode.io | sudo bash but when I run dappnode_start I get the following error.
project name can't be empty. Use "--project-name" to set a valid name. I think it is a docker version issue. When the bash script was written it appears that this flag was optional.
Im running on an Intel NUC, docker version: 20.10.24, docker-compose version: 1.29.2
Debian 12.
Went through all the yml files but can’t find where this option should been set…
Seems like there is a conflict between the expected docker version and the newest version that people get when installing docker.

**Comment by pablomendezroyo** [comment]
@fritzschoff hi there! have you executed before the pre-requistes script? check this out https://docs.dappnode.io/docs/user/install/script#prerequisites

I would say that there are some directories that need to exist.

Let me know if after running the prerequisites you are able to run the installer script

**Comment by fritzschoff** [comment]
Yes I did, all green and seems to be ready for the installer script

**Comment by alexpeterson91** [comment]
> Yes I did, all green and seems to be ready for the installer script

Are you still experiencing this issue or has it been resolved?
