### ISSUE TITLE
Error upgrading core to 0.2.50

### ISSUE THREAD

**Issue by blgalvin** [dappnode/DNP_CORE#79]
When i tried to upgrade Core to version 0.2.50, it throws an error that says "Core package dappmanager.dnp.dappnode.eth is from a foreign registry"

___________________________________________________________________________________
Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.49
dappmanager.dnp.dappnode.eth: 0.2.44, commit: 7c9a6772
https.dnp.dappnode.eth: 0.1.2
ipfs.dnp.dappnode.eth: 0.2.15
vpn.dnp.dappnode.eth: 0.2.8, commit: f9a8743e
wifi.dnp.dappnode.eth: 0.2.8
System info
dockerComposeVersion: 1.25.5
dockerServerVersion: 20.10.2
dockerCliVersion: 20.10.2
os: debian
versionCodename: bullseye
architecture: amd64
kernel: 5.10.0-6-amd64
Disk usage: 46%
______________________________________________________________

Actual Error - 

Error: Core package dappmanager.dnp.dappnode.eth is from a foreign registry
    at /usr/src/app/webpack:/@dappnode/dappmanager/src/calls/packageInstall.ts:60:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/index.js:261953:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

{
  "name": "core.dnp.dappnode.eth",
  "version": "0.2.50",
  "userSettings": {},
  "options": {}

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**DAppNode version:**

- Package version: 
- OS: 
- Browser 

**Additional context**

**Comment by pablomendezroyo** [comment]
@blgalvin hey! that issue can be easy fixed by upgrading your dappnode using the method described in the following forum post https://forum.dappnode.io/t/core-package-dappmanager-dnp-dappnode-eth-is-from-a-foreign-registry/1383
