### ISSUE TITLE
Consider upgrading hosts  Linux kernel to a secure and stable version

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_CORE#81]
Having the linux kernel out of date may become a security issue, there should be considered to upgrade the Linux kernel version to a stable and secure version.

**Comment by 3alpha** [comment]
Related to: dappnode/DNP_DAPPMANAGER/pull/959

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DNP_DAPPMANAGER/pull/959
